version: '3.8'

services:
  viktorbrain:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sessions:/app/sessions
    restart: unless-stopped
    networks:
      - viktor-network

  viktorai:
    build:
      context: ../ViktorAI
      dockerfile: Dockerfile.ai
    ports:
      - "8080:8080"
    environment:
      - BRAIN_API_URL=http://viktorbrain:8000
    depends_on:
      - viktorbrain
    restart: unless-stopped
    networks:
      - viktor-network

networks:
  viktor-network:
    driver: bridge 